service:
  default_host: 'localhost:3000'
  name: 'Game Reviewers'

slack:
  webhook_url: <%= ENV['SLACK_WEBHOOK_URL'] %>
  channel: <%= ENV['SLACK_CHANNEL_NAME'] %>

mail:
  reset_password: '【Game Reviewers】パスワード再設定手続きのご案内'